application: blockcylin
version: 1
runtime: go
api_version: go1

handlers:
- url: /(.+)
  static_files: build/web/\1
  upload: build/web/.*

- url: /
  static_files: build/web/index.html
  upload: build/web/index.html

